#At the top of your workflow file, create 4 environment variables:

#registryName - the full server address of your ACR instance. 
#Set this to “registryName.azurecr.io” - replacing registryName with the <prefix>devopsreg value in your ARM template file (line #26).
#repositoryName - The repository to target in the registry. 
#Set this to “wth/dotnetcoreapp”.
#dockerFolderPath - The path to the folder that contains the Dockerfile - a critical parameter. 
#You will need to point to the folder: Application/src/RazorPagesTestSample.
#tag - This needs to be a unique value each time, as this is used to version the images in the repository. 
#GitHub makes environment variables available that helps with this. 
#Set tag to the github.run_number environment variable.
      #To authenticate to the registry, add a step named Docker login with the following as the run command: docker login $registryName -u ACR_USERNAME -p ACR_PASSWORD - replacing ACR_USERNAME and ACR_PASSWORD with the secrets.

#To build your image, add a step named Docker build with the following as the run command: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

#To push your image to ACR, add a step named Docker push with the following as the run command: docker push $registryName/$repositoryName:$tag

name: Build and push Docker images

on:
    push:
        branches:
            - main

env:
    registryName: uud7b4siptma4wthreg.azurecr.io
    repositoryName: wth/dotnetcoreapp
    dockerFolderPath: Application/src/RazorPagesTestSample
    tag: ${{ github.run_number }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Docker login
              run: docker login $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

            - name: Docker build
              run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

            - name: Docker push
              run: docker push $registryName/$repositoryName:$tag
