env:
  registryName: uud7b4siptma4wthreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'

jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build
      run: dotnet build --no-restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  build-and-push-app-image-to-acr:
      needs: build-and-test-app
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Docker login
            run: docker login ${{ env.registryName }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

          - name: Docker build
            run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} --build-arg build_version=${{ env.tag }} ${{ env.dockerFolderPath }}

          - name: Docker push
            run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}
           
  deploy-to-dev:
    needs: build-and-push-app-image-to-acr
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
      url: http://uud7b4siptma4-test.azurewebsites.net
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

    - name: Deploy to Dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: uud7b4siptma4-dev
        images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-to-test:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment:
      name: 'test'
      url: http://uud7b4siptma4-test.azurewebsites.net
    steps:
    - name: Deploy to Test
      uses: azure/webapps-deploy@v2
      with:
        app-name: uud7b4siptma4-test
        images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-to-prod:
    needs: deploy-to-test
    runs-on: ubuntu-latest
    environment:
      name: 'prod'
      url: http://uud7b4siptma4-prod.azurewebsites.net
    steps:
    - name: Deploy to Prod
      uses: azure/webapps-deploy@v2
      with:
        app-name: uud7b4siptma4-prod
        images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}