name: CI

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "step1"
            - run: echo "step2"
    job2:
        name: CowAction
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - uses: mscoutermarsh/cowsays-action@master
              with:
                text: 'Giannis and Vijay say Be!'
                color: 'white'