name: afeez-first-workflow

on:
  workflow_dispatch
  
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Step One 
      run: echo "Running Step One!"
    - name: Step Two 
      run: echo "Running Step Two!"
      
  job2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
