name : My First Workflow

on:
   workflow_dispatch:
jobs:
  job1:
     runs-on: ubuntu-latest
     
     steps:
       - name: Step First
         run: echo "Running First Step!"
       - name: Step Two
         run: echo "Running Second Step!"
         
       
